### ISSUE TITLE
Can't launch game

### ISSUE THREAD

**Issue by hungnguyennaz** [Scarlaid/P-QoL#14]
Không start được game sau khi cài modpack 1.18.2
OS: Ubuntu 20.04 
![image](https://user-images.githubusercontent.com/101444336/159636216-eac60800-9128-4a1f-8ef8-b858c29ca9d5.png)

**Comment by Scarlaid** [comment]
Remove Borderless Mining in the modpack and use [this one](https://www.curseforge.com/minecraft/mc-mods/borderless-mining/files) instead

the one in the modpack is for Windows specific only

**Comment by hungnguyennaz** [comment]
Thanks, solved.
