### ISSUE TITLE
Suggestion to include a table of popular dependency mods

### ISSUE THREAD

**Issue by EndermanHackerVN** [Scarlaid/P-QoL#15]
Like [this](https://github.com/EndermanHackerVN/minimal-qol-modpack#dependency-mods)  
![image](https://user-images.githubusercontent.com/67498765/159718482-b32882a2-5fed-4ce6-9cc7-fd8c82a5d08d.png)

**Comment by Scarlaid** [comment]
make a pull request for it please, listing dependency mods are a pain for me since there are like 40+ of them
