### ISSUE TITLE
Adding ResolutionControl+

### ISSUE THREAD

**Issue by AyaneNacho** [Scarlaid/P-QoL#20]
adding this mod to increase performance for gpu or put less stress on gpu when u're using shader (Note: won't run when using fabulous graphics)
https://www.curseforge.com/minecraft/mc-mods/resolutioncontrol

**Comment by Scarlaid** [comment]
I will do testing as soon as I done fixing JVM with my PC

**Comment by Scarlaid** [comment]
Hello, after some testing, this mod will be marked as "optional" because this impacts heavily on people perspective with their quality or quantity view

**Comment by Scarlaid** [comment]
Nevermind, added to the modpack.
