### ISSUE TITLE
I keep crashing when I die

### ISSUE THREAD

**Issue by PenNamed** [Scarlaid/P-QoL#21]
I don't know which mod in the pack makes you instantly revive, or if there even is one. Each time I die, my game crashes because I don't think it can handle the instant respawn. Please help, thank you.

This is what the Minecraft launcher says: The game crashed whilst unexpected error Error: java.lang.StackOverflowError: Unexpected error. Exit Code: -1

**Comment by Scarlaid** [comment]
It's the mod issue, the AutoRevive from MineQuery does not seem to have a delay, which will hurt the game a bit until, it would crash, I will provide the config folder with this option off by default soon enough.

**Comment by Scarlaid** [comment]
the mod is now fixed
