### ISSUE TITLE
some lines of texts are blocking my framerate, how I can fix it?

### ISSUE THREAD

**Issue by Bachender9008** [Scarlaid/P-QoL#3]
Some lines of text are blocking my FPS. How can i fix it?
![2022-02-12_11 20 38](https://user-images.githubusercontent.com/99522860/153696510-6617aacb-a612-4207-aa20-e889bf7b2f82.png)

**Comment by Scarlaid** [comment]
The first layer is MiniHUD, you can turn it off in the Mods section 
The second layer is from Sodium Extra, you can turn it of in Video Settings > Extra option

**Comment by Scarlaid** [comment]
Go on the Mods option, find the MiniHUD mod then press this
![image](https://user-images.githubusercontent.com/90851437/153696961-4608eec0-c66a-40bf-b21f-13c92de184a5.png)
Go to Info Lines and **false** the mainRenderingToggle
The rendering is togglable with a hotkey so if you are willing to use it, bind the rendering with a hotkey
![image](https://user-images.githubusercontent.com/90851437/153696984-0ed69dae-3c07-4a40-80c5-9e6cab41198d.png)

**Comment by Bachender9008** [comment]
> Go on the Mods option, find the MiniHUD mod then press this ![image](https://user-images.githubusercontent.com/90851437/153696961-4608eec0-c66a-40bf-b21f-13c92de184a5.png) Go to Info Lines and **false** the mainRenderingToggle The rendering is togglable with a hotkey so if you are willing to use it, bind the rendering with a hotkey ![image](https://user-images.githubusercontent.com/90851437/153696984-0ed69dae-3c07-4a40-80c5-9e6cab41198d.png)

thanks!
