### ISSUE TITLE
Mod suggestions

### ISSUE THREAD

**Issue by azurenekowo** [Scarlaid/P-QoL#4]
The More Block Predicates mod url 404'd, please fix.

![kekw](https://user-images.githubusercontent.com/67498765/153708107-a7fb1538-0471-4f17-b0be-c44a83084828.png)

**Comment by Scarlaid** [comment]
Really wish I could found the mbp mod link again, somehow Modrinth link broke lol

**Comment by Scarlaid** [comment]
Alright, I found the link and replaced the Modrinth link with a Github one because why not lol
